#!/usr/bin/env bash
# create_env.sh — Spin up a new isolated sandbox environment
# Usage: ./create_env.sh <name> [ttl_seconds]
set -euo pipefail

# ── Resolve absolute paths regardless of where the script is called from ──────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load .env if present
# shellcheck source=/dev/null
[[ -f "$ROOT_DIR/.env" ]] && source "$ROOT_DIR/.env"

# ── Config (all overridable via .env) ─────────────────────────────────────────
NAME="${1:-sandbox}"
TTL="${2:-${SANDBOX_DEFAULT_TTL:-1800}}"
NGINX_CONTAINER="${NGINX_CONTAINER:-sandbox-nginx}"
PLATFORM_NETWORK="${PLATFORM_NETWORK:-sandbox-platform}"
DEMO_IMAGE="${DEMO_IMAGE:-sandbox-demo-app}"
ENVS_DIR="$ROOT_DIR/envs"
NGINX_CONF_DIR="$ROOT_DIR/nginx/conf.d"
LOGS_DIR="$ROOT_DIR/logs"
APP_PORT=3000

mkdir -p "$ENVS_DIR" "$NGINX_CONF_DIR" "$LOGS_DIR"

# ── Generate unique environment ID ────────────────────────────────────────────
RAND=$(openssl rand -hex 3)
ENV_ID="env-${RAND}"
CONTAINER_NAME="sandbox-app-${ENV_ID}"
CREATED_AT=$(date +%s)

echo "🚀  Creating environment: $NAME  (ID: $ENV_ID)"

# ── Ensure the platform network exists ────────────────────────────────────────
if ! docker network inspect "$PLATFORM_NETWORK" &>/dev/null; then
  echo "   Creating platform network: $PLATFORM_NETWORK"
  docker network create "$PLATFORM_NETWORK"
fi

# ── Create a dedicated per-env network (for env-internal isolation) ───────────
ENV_NETWORK="sandbox-net-${ENV_ID}"
docker network create "$ENV_NETWORK"

# ── Start the demo app container ──────────────────────────────────────────────
CONTAINER_ID=$(docker run -d \
  --name "$CONTAINER_NAME" \
  --network "$PLATFORM_NETWORK" \
  --label "sandbox.env=$ENV_ID" \
  --label "sandbox.name=$NAME" \
  --label "sandbox.managed=true" \
  -e "ENV_ID=$ENV_ID" \
  -e "ENV_NAME=$NAME" \
  "$DEMO_IMAGE")

# Also connect to per-env isolated network
docker network connect "$ENV_NETWORK" "$CONTAINER_NAME"

# ── Write nginx per-env config ────────────────────────────────────────────────
NGINX_CONF="$NGINX_CONF_DIR/${ENV_ID}.conf"
cat > "${NGINX_CONF}.tmp" <<NGINX
# Auto-generated by create_env.sh — do not edit manually
# ENV: $ENV_ID  NAME: $NAME  CREATED: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
location /envs/${ENV_ID}/ {
    proxy_pass         http://${CONTAINER_NAME}:${APP_PORT}/;
    proxy_http_version 1.1;
    proxy_set_header   Host              \$host;
    proxy_set_header   X-Real-IP         \$remote_addr;
    proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Prefix /envs/${ENV_ID};
    proxy_set_header   Upgrade           \$http_upgrade;
    proxy_set_header   Connection        "upgrade";
    proxy_read_timeout 30s;
    proxy_connect_timeout 5s;
}
NGINX
mv "${NGINX_CONF}.tmp" "$NGINX_CONF"

# Reload nginx
if docker inspect "$NGINX_CONTAINER" &>/dev/null; then
  docker exec "$NGINX_CONTAINER" nginx -s reload
  echo "   Nginx reloaded ✓"
else
  echo "   ⚠  Nginx container '$NGINX_CONTAINER' not found — skipping reload"
fi

# ── Start log shipping (Approach A) ──────────────────────────────────────────
ENV_LOG_DIR="$LOGS_DIR/$ENV_ID"
mkdir -p "$ENV_LOG_DIR"
nohup docker logs -f "$CONTAINER_NAME" >> "$ENV_LOG_DIR/app.log" 2>&1 &
LOG_PID=$!
echo "$LOG_PID" > "$ENV_LOG_DIR/log_shipper.pid"
echo "   Log shipper started (PID: $LOG_PID) ✓"

# ── Write state file atomically ────────────────────────────────────────────────
STATE_FILE="$ENVS_DIR/${ENV_ID}.json"
EXPIRES_AT=$((CREATED_AT + TTL))
cat > "${STATE_FILE}.tmp" <<JSON
{
  "id": "$ENV_ID",
  "name": "$NAME",
  "container_id": "$CONTAINER_ID",
  "container_name": "$CONTAINER_NAME",
  "env_network": "$ENV_NETWORK",
  "created_at": $CREATED_AT,
  "expires_at": $EXPIRES_AT,
  "ttl": $TTL,
  "status": "running",
  "url": "http://localhost/envs/${ENV_ID}/",
  "health_url": "http://localhost/envs/${ENV_ID}/health"
}
JSON
mv "${STATE_FILE}.tmp" "$STATE_FILE"
echo "   State written ✓"

# ── Summary ───────────────────────────────────────────────────────────────────
EXPIRES_HUMAN=$(date -d "@$EXPIRES_AT" '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null \
  || date -r "$EXPIRES_AT" '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null \
  || echo "in ${TTL}s")

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  Environment Created Successfully                ║"
echo "╠══════════════════════════════════════════════════╣"
printf "║  %-16s %-31s ║\n" "ID:"      "$ENV_ID"
printf "║  %-16s %-31s ║\n" "Name:"    "$NAME"
printf "║  %-16s %-31s ║\n" "URL:"     "http://localhost/envs/${ENV_ID}/"
printf "║  %-16s %-31s ║\n" "TTL:"     "${TTL}s"
printf "║  %-16s %-31s ║\n" "Expires:" "$EXPIRES_HUMAN"
echo "╚══════════════════════════════════════════════════╝"
